import type { EventCategory, EventItem, EventStatus } from "@/types";

export const eventCategories: Array<{ value: EventCategory | "all"; label: string }> = [
  { value: "all", label: "All categories" },
  { value: "technology", label: "Technology" },
  { value: "business", label: "Business" },
  { value: "community", label: "Community" },
  { value: "education", label: "Education" },
  { value: "creative", label: "Creative" },
];

export const eventStatuses: Array<{ value: EventStatus | "all"; label: string }> = [
  { value: "all", label: "Any status" },
  { value: "UPCOMING", label: "Upcoming" },
  { value: "ONGOING", label: "Ongoing" },
  { value: "COMPLETED", label: "Completed" },
  { value: "CANCELLED", label: "Cancelled" },
];

export const mockEvents: EventItem[] = [
  {
    id: "event-1",
    slug: "planora-product-summit",
    title: "Planora Product Summit",
    shortDescription: "A public strategy day for founders, PMs, and builders shipping ambitious products.",
    description:
      "Planora Product Summit brings together product leaders, startup founders, and growth teams for a full day of live talks, tactical workshops, and curated networking. Attendees will explore roadmap prioritization, user research systems, and launch storytelling with operators from fast-moving teams.",
    organizer: "Planora Studio",
    dateLabel: "April 18, 2026",
    timeLabel: "10:00 AM - 6:00 PM",
    venue: "Bangladesh Shilpakala Academy, Dhaka",
    visibility: "PUBLIC",
    feeType: "paid",
    feeLabel: "৳1200",
    category: "business",
    status: "UPCOMING",
    membersJoined: 132,
    membersCapacity: 220,
    coverTone: "from-[#0b5f52] via-[#187d68] to-[#f2cc73]",
  },
  {
    id: "event-2",
    slug: "midnight-dev-jam",
    title: "Midnight Dev Jam",
    shortDescription: "An after-hours coding sprint for frontend teams building experimental event products.",
    description:
      "Midnight Dev Jam is a high-energy collaborative build night designed for developers who want to prototype fast, learn from peers, and leave with working features. Expect lightning demos, mentor feedback, and a focused maker environment for event-tech ideas.",
    organizer: "Hackers of Dhaka",
    dateLabel: "April 22, 2026",
    timeLabel: "8:00 PM - 2:00 AM",
    venue: "Online on Planora Live",
    visibility: "PUBLIC",
    feeType: "free",
    feeLabel: "Free",
    category: "technology",
    status: "UPCOMING",
    membersJoined: 88,
    membersCapacity: 100,
    coverTone: "from-[#142233] via-[#26415c] to-[#8bb9a7]",
  },
  {
    id: "event-3",
    slug: "community-host-circle",
    title: "Community Host Circle",
    shortDescription: "A meetup for organizers who want to design more welcoming and memorable event communities.",
    description:
      "Community Host Circle is a conversation-led gathering focused on member retention, event rituals, and designing experiences people want to return to. Hosts will swap playbooks for onboarding, invitation design, and attendee follow-up.",
    organizer: "People & Places Collective",
    dateLabel: "April 25, 2026",
    timeLabel: "4:00 PM - 7:00 PM",
    venue: "Gulshan Lake View Lounge",
    visibility: "PUBLIC",
    feeType: "free",
    feeLabel: "Free",
    category: "community",
    status: "ONGOING",
    membersJoined: 54,
    membersCapacity: 120,
    coverTone: "from-[#5f3d24] via-[#b06d2f] to-[#f7dca4]",
  },
  {
    id: "event-4",
    slug: "ai-design-lab",
    title: "AI Design Lab",
    shortDescription: "A practical studio where designers explore AI-assisted workflows for product teams.",
    description:
      "AI Design Lab blends prompt-driven ideation, interface critique, and systems thinking into one hands-on workshop. Participants move from concepting to prototype reviews while discussing ethical design and collaboration patterns with engineers.",
    organizer: "Canvas Frontier",
    dateLabel: "May 2, 2026",
    timeLabel: "11:00 AM - 4:30 PM",
    venue: "Banani Creative Loft",
    visibility: "PUBLIC",
    feeType: "paid",
    feeLabel: "৳950",
    category: "creative",
    status: "UPCOMING",
    membersJoined: 71,
    membersCapacity: 80,
    coverTone: "from-[#6d314a] via-[#b85d76] to-[#f6c6b0]",
  },
  {
    id: "event-5",
    slug: "career-switch-bootcamp",
    title: "Career Switch Bootcamp",
    shortDescription: "An intensive event for learners moving into tech, product, and digital operations.",
    description:
      "Career Switch Bootcamp combines live mentorship, mock interviews, and portfolio feedback for aspiring professionals entering high-growth digital roles. Sessions cover positioning, networking, and job search momentum.",
    organizer: "Next Chapter Academy",
    dateLabel: "May 7, 2026",
    timeLabel: "9:30 AM - 5:00 PM",
    venue: "BRAC CDM, Rajendrapur",
    visibility: "PUBLIC",
    feeType: "paid",
    feeLabel: "৳1400",
    category: "education",
    status: "UPCOMING",
    membersJoined: 96,
    membersCapacity: 180,
    coverTone: "from-[#0b5065] via-[#1e7a9b] to-[#bde7f1]",
  },
  {
    id: "event-6",
    slug: "launch-night-market",
    title: "Launch Night Market",
    shortDescription: "A showcase night for makers, indie brands, and creative founders unveiling new work.",
    description:
      "Launch Night Market is built for creators who want to present new products in a tactile, social setting. Visitors can discover prototypes, talk directly with founders, and experience live storytelling sessions throughout the evening.",
    organizer: "Maker District",
    dateLabel: "May 11, 2026",
    timeLabel: "6:30 PM - 10:30 PM",
    venue: "Dhaka Design Yard",
    visibility: "PRIVATE",
    feeType: "free",
    feeLabel: "Free",
    category: "creative",
    status: "UPCOMING",
    membersJoined: 142,
    membersCapacity: 160,
    coverTone: "from-[#24375f] via-[#3d5f9f] to-[#eec27b]",
  },
];

export function getEventBySlug(slug: string) {
  return mockEvents.find((event) => event.slug === slug);
}
